---
title: "index.qmd"
author: "David Zuhlsdorf"
format: html
editor: visual
---

### How Much Do Missed Calls Matter? Umpire Accuracy and Potential Impact in the 2025 World Series

##### Abstract:
This project will look at umpire ball and strike call accuracy in the 2025 World Series using Statcast data from baseball savant. 



```{r}
# read in 2025 World Series data
library(tidyverse)
library(readxl)
library(plotly)
data<- read_excel(here::here("data/2025WS_data.xlsx"))

```

```{r}
# Need to make the strike zone and establish what is a strike or ball
data$plate_x <- as.numeric(data$plate_x)
data$plate_z <- as.numeric(data$plate_z)
clean_data <- data %>%
  filter(des == c("Ball","Called Strike")) %>%
  mutate(ump_call = if_else(des == "Called Strike","Strike","Ball"),
         abs_call = if_else(plate_x >= -0.83 & plate_x <= 0.83 &
                              plate_z >= sz_bot & plate_z <= sz_top,
                            "Strike",
                            "Ball"),
         correct_call = if_else(ump_call == abs_call,"Yes","No"),
         z_norm = (plate_z - sz_bot) / (sz_top - sz_bot)
         )

```

```{r}

ggplot(clean_data, aes(x = plate_x, y = z_norm, color = correct_call)) +
  geom_point(position = "jitter") +
geom_rect(
    xmin = -0.83, xmax = 0.83,
    ymin = 0, ymax = 1,
    fill = NA, color = "black", linewidth = 1
  ) +
  theme_minimal() +
  scale_color_viridis_d() +
  labs(
    title = "Correct and Incorrect Ball/Strike Calls",
    x = "Horizontal pitch location (plate_x)",
    y = "Normalized strike zone height",
    color = "Correct Call"
  ) 
  
```

```{r}
# overall accuracy bar chart 
accuracy_data <- clean_data %>%
  group_by(game_date) %>%
  count(correct_call) %>%
  mutate(game_date = as.character(game_date),
    accuracy = (n / sum(n))*100) %>%
  filter(correct_call == "Yes")

barplot<- ggplot(accuracy_data,aes(x = game_date, y = accuracy, fill = accuracy, label = accuracy)) +
  geom_col() +
  theme_minimal() +
  scale_fill_viridis_c() +
  geom_hline(aes(yintercept = 94.15,
             linetype = "2025 Average Accuracy:94.15%")) +
  labs(title = "Umpire Accuracy for Called Pitches in 2025 World Series")

ggplotly(barplot,tooltip = "label")

```

```{r}
# Missed call density heatmap
missed_calls <- clean_data %>%
  filter(correct_call == "No")

ggplot(missed_calls, aes(x = plate_x, y = z_norm)) +
  stat_density_2d(
    aes(fill = after_stat(density)),
    geom = "raster",
    contour = FALSE
  ) +
  geom_rect(
    xmin = -0.83, xmax = 0.83,
    ymin = 0, ymax = 1,
    fill = NA, color = "white", linewidth = 1
  ) +
  scale_fill_viridis_c() +
  theme_minimal() +
  labs(
    title = "Density of Missed Ball/Strike Calls in 2025 World Series",
    x = "Horizontal Pitch Location",
    y = "Normalized Strike Zone Height",
    fill = "Density"
  )
```

